### ISSUE TITLE
??

### ISSUE THREAD

**Issue by jaylac2000** [LukeWasTakenn/luke_multicharacter#1]
I edited the es_extended code, tried to start and this happened...
![Untitled](https://user-images.githubusercontent.com/53111006/116692106-5f66b380-a9ab-11eb-87a3-eff042715f0b.png)

**Comment by LukeWasTakenn** [comment]
![image](https://user-images.githubusercontent.com/39926192/116693812-b4f88b80-a9be-11eb-8d06-e663152a2628.png)
